export const gymOwnerCopy = {
  vi: {
    entry: {
      statusLabel: 'Trạng thái hồ sơ',
      title: 'Hoàn thiện hồ sơ đối tác',
      required: 'Thông tin cần hoàn thành',
      continue: 'Tiếp tục thiết lập',
      viewStatus: 'Xem trạng thái phê duyệt',
    },
    steps: {
      overview: 'Tổng quan',
      profile: 'Thương hiệu & chi nhánh',
      license: 'Giấy phép kinh doanh',
      review: 'Xem lại & gửi',
      status: 'Phê duyệt',
      complete: 'Đã hoàn thành',
      incomplete: 'Chưa hoàn thành',
      current: 'Đang thực hiện',
    },
    status: {
      draft: 'Bản nháp',
      submitted: 'Đã gửi',
      under_review: 'Đang xét duyệt',
      approved: 'Đã phê duyệt',
      rejected: 'Cần chỉnh sửa',
    },
    profile: {
      step: 'Bước 1 / 3',
      brandSection: 'Thông tin thương hiệu',
      branchSection: 'Thông tin chi nhánh',
      brandName: 'Tên thương hiệu phòng tập',
      brandDescription: 'Mô tả trên Marketplace',
      contactPhone: 'Số điện thoại liên hệ',
      branchName: 'Tên chi nhánh',
      city: 'Tỉnh / Thành phố',
      area: 'Khu vực',
      address: 'Địa chỉ',
      operatingHours: 'Giờ hoạt động',
      facilities: 'Tiện ích',
      addBranch: 'Thêm chi nhánh',
      removeBranch: 'Xóa chi nhánh',
      save: 'Lưu và tiếp tục',
      back: 'Quay lại',
      requiredError: 'Vui lòng điền đầy đủ trường bắt buộc.',
      branchesError: 'Cần có ít nhất một chi nhánh.',
      branchLabel: 'Chi nhánh',
    },
    license: {
      step: 'Bước 2 / 3',
      section: 'Giấy phép kinh doanh',
      upload: 'Chọn tệp giấy phép',
      replace: 'Thay tệp',
      remove: 'Xóa tệp',
      accepted: 'Định dạng được hỗ trợ: PDF, PNG, JPG hoặc JPEG.',
      invalidType: 'Tệp không đúng định dạng được hỗ trợ.',
      tooLarge: 'Tệp vượt quá giới hạn 10 MB.',
      requiredError: 'Vui lòng tải lên giấy phép kinh doanh.',
      uploaded: 'Đã chọn tệp',
      save: 'Lưu và tiếp tục',
      back: 'Quay lại',
    },
    review: {
      step: 'Bước 3 / 3',
      brand: 'Thương hiệu',
      branches: 'Chi nhánh',
      license: 'Giấy phép kinh doanh',
      edit: 'Chỉnh sửa',
      submit: 'Gửi hồ sơ',
      resubmit: 'Gửi lại hồ sơ',
      back: 'Quay lại',
      confirmationTitle: 'Xác nhận gửi hồ sơ',
      confirmationBody: 'Thông tin sẽ được gửi để Platform Admin xét duyệt.',
      cancel: 'Hủy',
      confirm: 'Xác nhận gửi',
      confirmResubmit: 'Xác nhận gửi lại',
      submitting: 'Đang gửi…',
      incomplete: 'Hồ sơ chưa đầy đủ. Hãy hoàn thành thông tin và giấy phép trước khi gửi.',
      success: 'Hồ sơ đã được lưu và gửi xét duyệt.',
    },
    approval: {
      submittedTitle: 'Hồ sơ đã được gửi',
      submittedBody: 'Platform Admin sẽ tiếp nhận hồ sơ và chuyển sang bước xét duyệt.',
      reviewTitle: 'Hồ sơ đang được xét duyệt',
      reviewBody:
        'Bạn có thể theo dõi trạng thái tại đây. Thông tin đã gửi chỉ được chỉnh sửa khi có yêu cầu.',
      approvedTitle: 'Hồ sơ đã được phê duyệt',
      approvedBody: 'Thương hiệu của bạn đủ điều kiện hoạt động trên Marketplace.',
      rejectedTitle: 'Hồ sơ cần được chỉnh sửa',
      rejectedBody: 'Hãy cập nhật nội dung được yêu cầu và gửi lại hồ sơ.',
      reason: 'Nội dung cần chỉnh sửa',
      noReason: 'Platform Admin chưa cung cấp nội dung chi tiết.',
      edit: 'Chỉnh sửa hồ sơ',
      dashboard: 'Đi tới Dashboard',
      submittedAt: 'Gửi gần nhất',
      submissionCount: 'Số lần gửi',
    },
    facilities: [
      'Khu tạ tự do',
      'Khu cardio',
      'Khu functional',
      'Tủ đồ và phòng tắm',
      'Bãi đỗ xe',
      'Phòng xông hơi',
      'Khu phục hồi',
      'Đánh giá thể trạng',
    ],
  },
  en: {
    entry: {
      statusLabel: 'Application status',
      title: 'Complete your partner profile',
      required: 'Required information',
      continue: 'Continue setup',
      viewStatus: 'View approval status',
    },
    steps: {
      overview: 'Overview',
      profile: 'Brand & branches',
      license: 'Business license',
      review: 'Review & submit',
      status: 'Approval',
      complete: 'Complete',
      incomplete: 'Incomplete',
      current: 'In progress',
    },
    status: {
      draft: 'Draft',
      submitted: 'Submitted',
      under_review: 'Under review',
      approved: 'Approved',
      rejected: 'Changes required',
    },
    profile: {
      step: 'Step 1 of 3',
      brandSection: 'Brand information',
      branchSection: 'Branch information',
      brandName: 'Gym brand name',
      brandDescription: 'Marketplace description',
      contactPhone: 'Contact phone',
      branchName: 'Branch name',
      city: 'Province / City',
      area: 'Area',
      address: 'Address',
      operatingHours: 'Operating hours',
      facilities: 'Facilities',
      addBranch: 'Add branch',
      removeBranch: 'Remove branch',
      save: 'Save and continue',
      back: 'Back',
      requiredError: 'Complete every required field.',
      branchesError: 'At least one branch is required.',
      branchLabel: 'Branch',
    },
    license: {
      step: 'Step 2 of 3',
      section: 'Business license',
      upload: 'Choose license file',
      replace: 'Replace file',
      remove: 'Remove file',
      accepted: 'Supported formats: PDF, PNG, JPG or JPEG.',
      invalidType: 'This file format is not supported.',
      tooLarge: 'The file exceeds the 10 MB limit.',
      requiredError: 'Upload a business license before continuing.',
      uploaded: 'Selected file',
      save: 'Save and continue',
      back: 'Back',
    },
    review: {
      step: 'Step 3 of 3',
      brand: 'Brand',
      branches: 'Branches',
      license: 'Business license',
      edit: 'Edit',
      submit: 'Submit application',
      resubmit: 'Resubmit application',
      back: 'Back',
      confirmationTitle: 'Confirm application submission',
      confirmationBody: 'Your information will be sent to Platform Admin for review.',
      cancel: 'Cancel',
      confirm: 'Confirm submission',
      confirmResubmit: 'Confirm resubmission',
      submitting: 'Submitting…',
      incomplete:
        'The application is incomplete. Finish the profile and license before submitting.',
      success: 'The application was saved and submitted for review.',
    },
    approval: {
      submittedTitle: 'Application submitted',
      submittedBody: 'Platform Admin will receive the application and begin the review process.',
      reviewTitle: 'Application under review',
      reviewBody:
        'Track the status here. Submitted information can be edited when changes are requested.',
      approvedTitle: 'Application approved',
      approvedBody: 'Your brand is eligible to participate in the Marketplace.',
      rejectedTitle: 'Application changes required',
      rejectedBody: 'Update the requested information and resubmit the application.',
      reason: 'Required correction',
      noReason: 'Platform Admin has not provided detailed feedback.',
      edit: 'Edit application',
      dashboard: 'Go to Dashboard',
      submittedAt: 'Last submitted',
      submissionCount: 'Submission count',
    },
    facilities: [
      'Free weights',
      'Cardio floor',
      'Functional zone',
      'Locker & shower',
      'Parking',
      'Sauna',
      'Recovery zone',
      'Body assessment',
    ],
  },
} as const;

export type GymOwnerCopy = (typeof gymOwnerCopy)[keyof typeof gymOwnerCopy];
