export const gymOwnerAccountCopy = {
  vi: {
    notifications: 'Thông báo trong hệ thống',
    unread: 'Chưa đọc',
    read: 'Đã đọc',
    open: 'Mở nội dung liên quan',
    markRead: 'Đánh dấu đã đọc',
    loadingNotifications: 'Đang tải thông báo',
    emptyNotifications: 'Hiện chưa có thông báo dành cho Gym Owner.',
    errorNotifications: 'Không thể tải thông báo.',
    accountSecurity: 'Tài khoản & bảo mật',
    emailOtp: 'Xác minh email OTP',
    mandatoryEverySession: 'Bắt buộc ở mỗi phiên đăng nhập mới',
    registeredEmail: 'Email đăng ký',
    backendPolicy:
      'Độ dài mã, thời gian hết hạn, gửi lại và số lần thử do dịch vụ xác thực quản lý.',
    protected: 'Đang bảo vệ',
    importantActivity: 'Hoạt động quan trọng',
    activityBoundary: 'Chỉ hiển thị thời gian, hành động, ngữ cảnh cần thiết và kết quả.',
    dateTime: 'Thời gian',
    activity: 'Hoạt động',
    context: 'Ngữ cảnh',
    result: 'Kết quả',
    success: 'Thành công',
    submitted: 'Đã gửi',
    loadingActivity: 'Đang tải nhật ký hoạt động',
    emptyActivity: 'Chưa ghi nhận hoạt động quan trọng.',
    errorActivity: 'Không thể tải nhật ký hoạt động.',
  },
  en: {
    notifications: 'In-system notifications',
    unread: 'Unread',
    read: 'Read',
    open: 'Open related content',
    markRead: 'Mark as read',
    loadingNotifications: 'Loading notifications',
    emptyNotifications: 'There are currently no Gym Owner notifications.',
    errorNotifications: 'Notifications could not be loaded.',
    accountSecurity: 'Account & security',
    emailOtp: 'Email OTP verification',
    mandatoryEverySession: 'Required for every new sign-in session',
    registeredEmail: 'Registered email',
    backendPolicy:
      'Code length, expiry, resend, and attempt limits are managed by the authentication service.',
    protected: 'Protected',
    importantActivity: 'Important activity',
    activityBoundary: 'Only time, action, required context, and result are displayed.',
    dateTime: 'Date / time',
    activity: 'Activity',
    context: 'Context',
    result: 'Result',
    success: 'Success',
    submitted: 'Submitted',
    loadingActivity: 'Loading important activity',
    emptyActivity: 'No important activity has been recorded.',
    errorActivity: 'Important activity could not be loaded.',
  },
} as const;

export type GymOwnerAccountCopy = (typeof gymOwnerAccountCopy)[keyof typeof gymOwnerAccountCopy];
