export const gymOwnerTrainingCopy = {
  vi: {
    trainers: 'Trainer',
    trainerList: 'Danh sách Trainer',
    createTrainer: 'Tạo hồ sơ Trainer',
    assignmentExceptions: 'Ngoại lệ phân công',
    viewDetail: 'Xem chi tiết',
    edit: 'Chỉnh sửa',
    save: 'Lưu hồ sơ',
    saving: 'Đang lưu…',
    cancel: 'Hủy',
    back: 'Quay lại danh sách',
    fullName: 'Họ và tên',
    email: 'Email',
    phone: 'Số điện thoại',
    bio: 'Bio chuyên môn',
    selfIntroduction: 'Tự giới thiệu',
    experience: 'Số năm kinh nghiệm',
    specializations: 'Chuyên môn',
    avatar: 'Ảnh đại diện',
    uploadAvatar: 'Tải ảnh lên',
    imageRule: 'JPG, PNG hoặc WebP, tối đa 2 MB.',
    invalidImage: 'Ảnh phải là JPG, PNG hoặc WebP và không vượt quá 2 MB.',
    requiredTrainer: 'Hãy hoàn thành tên, email, bio, kinh nghiệm và ít nhất một chuyên môn.',
    savedTrainer: 'Đã lưu hồ sơ Trainer.',
    createdTrainer: 'Đã tạo hồ sơ Trainer ở trạng thái nháp.',
    approvalStatus: 'Trạng thái phê duyệt',
    operationalStatus: 'Trạng thái vận hành',
    approval: {
      draft: 'Nháp',
      pending: 'Chờ Platform duyệt',
      approved: 'Đã được Platform duyệt',
      rejected: 'Bị từ chối',
    },
    operational: {
      active: 'Đang hoạt động',
      hidden: 'Đã ẩn',
      suspended: 'Tạm ngưng',
      unlinked: 'Đã ngắt liên kết',
      unavailable: 'Chưa áp dụng',
    },
    specializationsMap: {
      strength: 'Sức mạnh',
      hypertrophy: 'Tăng cơ',
      fat_loss: 'Giảm mỡ',
      movement: 'Chất lượng vận động',
      mobility: 'Linh hoạt',
      endurance: 'Sức bền',
      rehabilitation: 'Phục hồi vận động',
    },
    years: 'năm',
    contact: 'Thông tin liên hệ',
    about: 'Thông tin chuyên môn',
    assignedMembers: 'Member đang được phân công',
    noAssignments: 'Trainer này chưa có phân công Member.',
    submitApproval: 'Gửi Platform xét duyệt',
    resubmitApproval: 'Gửi lại để xét duyệt',
    submitTitle: 'Gửi hồ sơ Trainer?',
    submitBody: 'Hồ sơ sẽ bị khóa chỉnh sửa trong khi Platform đang xét duyệt.',
    confirmSubmit: 'Xác nhận gửi',
    submitted: 'Hồ sơ Trainer đã được gửi cho Platform Admin.',
    pendingBody: 'Platform Admin đang xét duyệt hồ sơ. Gym Owner không thể tự phê duyệt.',
    approvedBody: 'Platform đã phê duyệt hồ sơ Trainer.',
    rejectionReason: 'Lý do từ chối',
    rejectedBody: 'Chỉnh sửa hồ sơ theo lý do từ chối, sau đó gửi lại cho Platform.',
    draftBody: 'Hoàn thiện hồ sơ trước khi gửi Platform xét duyệt.',
    statusActions: 'Quản lý trạng thái',
    hideTrainer: 'Ẩn Trainer',
    suspendTrainer: 'Tạm ngưng Trainer',
    restoreTrainer: 'Khôi phục hoạt động',
    unlinkTrainer: 'Ngắt liên kết',
    statusConfirmTitle: 'Xác nhận thay đổi trạng thái?',
    statusConfirmBody: 'Thay đổi được lưu vào trạng thái vận hành của Trainer.',
    unlinkWarning: 'Unlinked là trạng thái cuối và không thể khôi phục.',
    confirm: 'Xác nhận',
    statusUpdated: 'Đã cập nhật trạng thái Trainer.',
    noTrainers: 'Chưa có hồ sơ Trainer.',
    listError: 'Không thể tải danh sách Trainer.',
    loading: 'Đang tải dữ liệu',
    assignments: 'Phân công',
    active: 'Đang hoạt động',
    historical: 'Lịch sử',
    period: 'Thời hạn',
    member: 'Member',
    originalTrainer: 'Trainer ban đầu',
    replacementTrainer: 'Trainer thay thế',
    exceptionReason: {
      trainerUnavailable: 'Trainer không còn khả dụng',
      activationFailed: 'Không thể tự động kích hoạt phân công',
    },
    exceptionOpen: 'Cần xử lý',
    exceptionResolved: 'Đã xử lý',
    resolveException: 'Chọn Trainer thay thế',
    resolveTitle: 'Xử lý ngoại lệ phân công',
    resolveBody: 'Chỉ Trainer đã được phê duyệt và đang Active mới có thể nhận phân công.',
    chooseTrainer: 'Chọn Trainer',
    confirmAssignment: 'Xác nhận phân công',
    assignmentResolved: 'Đã xử lý ngoại lệ và cập nhật phân công.',
    noOpenExceptions: 'Không có ngoại lệ phân công cần xử lý.',
    packages: 'Gói PT',
    createPackage: 'Tạo gói PT',
    packageNameEn: 'Tên gói — tiếng Anh',
    packageNameVi: 'Tên gói — tiếng Việt',
    packageTrainer: 'Trainer phụ trách',
    sessions: 'Số buổi',
    durationDays: 'Số ngày hiệu lực',
    servicePrice: 'Giá dịch vụ Gym (VND)',
    featuresEn: 'Quyền lợi — tiếng Anh',
    featuresVi: 'Quyền lợi — tiếng Việt',
    oneFeaturePerLine: 'Mỗi dòng là một quyền lợi; hai ngôn ngữ phải có cùng số dòng.',
    packageStatus: 'Trạng thái xuất bản',
    draft: 'Nháp',
    published: 'Đã xuất bản',
    editPackage: 'Chỉnh sửa gói PT',
    savePackage: 'Lưu bản nháp',
    requiredPackage: 'Hãy hoàn thành tất cả trường và nhập quyền lợi song ngữ tương ứng.',
    packageCreated: 'Đã tạo gói PT ở trạng thái nháp.',
    packageSaved: 'Đã lưu thay đổi gói PT.',
    publish: 'Xuất bản',
    publishTitle: 'Xuất bản gói PT?',
    publishBody: 'Gói PT sẽ xuất hiện trong Marketplace sau khi xác nhận.',
    confirmPublish: 'Xác nhận xuất bản',
    packagePublished: 'Gói PT đã được xuất bản.',
    unpublish: 'Gỡ xuất bản',
    unpublishPending: 'Quy tắc trạng thái sau khi gỡ xuất bản đang chờ xác nhận.',
    noPackages: 'Chưa có gói PT.',
    packageListError: 'Không thể tải danh sách gói PT.',
  },
  en: {
    trainers: 'Trainers',
    trainerList: 'Trainer list',
    createTrainer: 'Create Trainer profile',
    assignmentExceptions: 'Assignment exceptions',
    viewDetail: 'View details',
    edit: 'Edit',
    save: 'Save profile',
    saving: 'Saving…',
    cancel: 'Cancel',
    back: 'Back to list',
    fullName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    bio: 'Professional bio',
    selfIntroduction: 'Self-introduction',
    experience: 'Years of experience',
    specializations: 'Specializations',
    avatar: 'Profile photo',
    uploadAvatar: 'Upload photo',
    imageRule: 'JPG, PNG or WebP, up to 2 MB.',
    invalidImage: 'The photo must be JPG, PNG or WebP and no larger than 2 MB.',
    requiredTrainer: 'Complete name, email, bio, experience and at least one specialization.',
    savedTrainer: 'Trainer profile saved.',
    createdTrainer: 'Trainer profile created as a draft.',
    approvalStatus: 'Approval status',
    operationalStatus: 'Operational status',
    approval: {
      draft: 'Draft',
      pending: 'Pending Platform approval',
      approved: 'Platform approved',
      rejected: 'Rejected',
    },
    operational: {
      active: 'Active',
      hidden: 'Hidden',
      suspended: 'Suspended',
      unlinked: 'Unlinked',
      unavailable: 'Not applicable',
    },
    specializationsMap: {
      strength: 'Strength',
      hypertrophy: 'Hypertrophy',
      fat_loss: 'Fat loss',
      movement: 'Movement quality',
      mobility: 'Mobility',
      endurance: 'Endurance',
      rehabilitation: 'Exercise rehabilitation',
    },
    years: 'years',
    contact: 'Contact information',
    about: 'Professional information',
    assignedMembers: 'Assigned Members',
    noAssignments: 'This Trainer has no Member assignments.',
    submitApproval: 'Submit for Platform approval',
    resubmitApproval: 'Resubmit for approval',
    submitTitle: 'Submit this Trainer profile?',
    submitBody: 'The profile will be locked for editing while Platform review is pending.',
    confirmSubmit: 'Confirm submission',
    submitted: 'Trainer profile submitted to Platform Admin.',
    pendingBody: 'Platform Admin is reviewing this profile. Gym Owner cannot approve it.',
    approvedBody: 'Platform has approved this Trainer profile.',
    rejectionReason: 'Rejection reason',
    rejectedBody: 'Edit the profile using the rejection reason, then resubmit it to Platform.',
    draftBody: 'Complete the profile before submitting it for Platform approval.',
    statusActions: 'Manage status',
    hideTrainer: 'Hide Trainer',
    suspendTrainer: 'Suspend Trainer',
    restoreTrainer: 'Restore Active status',
    unlinkTrainer: 'Unlink Trainer',
    statusConfirmTitle: 'Confirm status change?',
    statusConfirmBody: "This change will update the Trainer's operational status.",
    unlinkWarning: 'Unlinked is terminal and cannot be restored.',
    confirm: 'Confirm',
    statusUpdated: 'Trainer status updated.',
    noTrainers: 'No Trainer profiles are available.',
    listError: 'The Trainer list could not be loaded.',
    loading: 'Loading data',
    assignments: 'Assignments',
    active: 'Active',
    historical: 'Historical',
    period: 'Period',
    member: 'Member',
    originalTrainer: 'Original Trainer',
    replacementTrainer: 'Replacement Trainer',
    exceptionReason: {
      trainerUnavailable: 'Trainer is unavailable',
      activationFailed: 'Automatic assignment activation failed',
    },
    exceptionOpen: 'Needs action',
    exceptionResolved: 'Resolved',
    resolveException: 'Choose replacement Trainer',
    resolveTitle: 'Resolve assignment exception',
    resolveBody: 'Only Platform-approved Trainers with Active status can receive an assignment.',
    chooseTrainer: 'Choose Trainer',
    confirmAssignment: 'Confirm assignment',
    assignmentResolved: 'Exception resolved and assignment updated.',
    noOpenExceptions: 'There are no assignment exceptions requiring action.',
    packages: 'PT packages',
    createPackage: 'Create PT package',
    packageNameEn: 'Package name — English',
    packageNameVi: 'Package name — Vietnamese',
    packageTrainer: 'Assigned Trainer',
    sessions: 'Sessions included',
    durationDays: 'Validity in days',
    servicePrice: 'Gym service price (VND)',
    featuresEn: 'Features — English',
    featuresVi: 'Features — Vietnamese',
    oneFeaturePerLine: 'One feature per line; both languages must have the same number of lines.',
    packageStatus: 'Publication status',
    draft: 'Draft',
    published: 'Published',
    editPackage: 'Edit PT package',
    savePackage: 'Save draft',
    requiredPackage: 'Complete every field and provide matching bilingual feature lines.',
    packageCreated: 'PT package created as a draft.',
    packageSaved: 'PT package changes saved.',
    publish: 'Publish',
    publishTitle: 'Publish this PT package?',
    publishBody: 'The PT package will appear in Marketplace after confirmation.',
    confirmPublish: 'Confirm publication',
    packagePublished: 'PT package published.',
    unpublish: 'Unpublish',
    unpublishPending: 'The post-unpublish state rule is awaiting confirmation.',
    noPackages: 'No PT packages are available.',
    packageListError: 'The PT package list could not be loaded.',
  },
} as const;

export type GymOwnerTrainingCopy = (typeof gymOwnerTrainingCopy)[keyof typeof gymOwnerTrainingCopy];
