export const gymOwnerDashboardCopy = {
  vi: {
    dashboard: 'Bảng điều khiển',
    customize: 'Tùy chỉnh bảng điều khiển',
    preferencesSaved: 'Đã lưu bố cục bảng điều khiển.',
    widgets: {
      trainers: 'Trainer',
      assignments: 'Phân công',
      ptSales: 'Bán gói PT',
      appointments: 'Lịch hẹn',
      alerts: 'Cảnh báo vận hành',
    },
    records: 'bản ghi',
    trainerTotal: 'Tổng hồ sơ Trainer',
    trainerStatuses: {
      active: 'Đang hoạt động',
      hidden: 'Đã ẩn',
      suspended: 'Tạm ngưng',
      unlinked: 'Đã ngắt liên kết',
    },
    assignmentStatuses: {
      active: 'Đang hoạt động',
      historical: 'Lịch sử',
    },
    member: 'Member',
    trainer: 'Trainer',
    period: 'Thời hạn',
    purchaseStatuses: {
      confirmed: 'Đã xác nhận',
      pending: 'Đang xử lý',
    },
    appointmentStatuses: {
      confirmed: 'Đã xác nhận',
      pending: 'Chờ xác nhận',
      cancelled: 'Đã hủy',
    },
    appointmentTypes: {
      assessment: 'Đánh giá ban đầu',
      coaching: 'Huấn luyện PT',
      planReview: 'Rà soát kế hoạch',
    },
    severity: {
      high: 'Ưu tiên cao',
      medium: 'Ưu tiên trung bình',
      low: 'Sắp tới',
    },
    alertMessages: {
      assignmentRequired: 'Giao dịch gói PT cần được phân công Trainer',
      trainerReviewPending: 'Hồ sơ Trainer đang chờ Platform xét duyệt',
      appointmentCancelled: 'Lịch hẹn đã bị hủy và cần được theo dõi',
      appointmentUpcoming: 'Lịch hẹn sắp diễn ra',
    },
    states: {
      loading: 'Đang tải dữ liệu',
      error: 'Không thể tải dữ liệu của mục này.',
      empty: {
        trainers: 'Chưa có hồ sơ Trainer.',
        assignments: 'Chưa có phân công Trainer–Member.',
        ptSales: 'Chưa có giao dịch gói PT.',
        appointments: 'Chưa có lịch hẹn.',
        alerts: 'Hiện không có cảnh báo vận hành.',
      },
    },
    customization: {
      title: 'Tùy chỉnh bảng điều khiển',
      description: 'Chọn các mục cần hiển thị và sắp xếp thứ tự của chúng.',
      showWidget: 'Hiển thị',
      moveUp: 'Di chuyển lên',
      moveDown: 'Di chuyển xuống',
      reset: 'Đặt lại',
      cancel: 'Hủy',
      save: 'Lưu bố cục',
    },
    allHidden: 'Tất cả mục trên bảng điều khiển đang được ẩn.',
    showWidgets: 'Chọn mục hiển thị',
  },
  en: {
    dashboard: 'Dashboard',
    customize: 'Customize dashboard',
    preferencesSaved: 'Dashboard layout saved.',
    widgets: {
      trainers: 'Trainers',
      assignments: 'Assignments',
      ptSales: 'PT sales',
      appointments: 'Appointments',
      alerts: 'Operational alerts',
    },
    records: 'records',
    trainerTotal: 'Total Trainer records',
    trainerStatuses: {
      active: 'Active',
      hidden: 'Hidden',
      suspended: 'Suspended',
      unlinked: 'Unlinked',
    },
    assignmentStatuses: {
      active: 'Active',
      historical: 'Historical',
    },
    member: 'Member',
    trainer: 'Trainer',
    period: 'Period',
    purchaseStatuses: {
      confirmed: 'Confirmed',
      pending: 'Processing',
    },
    appointmentStatuses: {
      confirmed: 'Confirmed',
      pending: 'Pending',
      cancelled: 'Cancelled',
    },
    appointmentTypes: {
      assessment: 'Initial assessment',
      coaching: 'PT coaching',
      planReview: 'Plan review',
    },
    severity: {
      high: 'High priority',
      medium: 'Medium priority',
      low: 'Upcoming',
    },
    alertMessages: {
      assignmentRequired: 'A PT package purchase needs a Trainer assignment',
      trainerReviewPending: 'A Trainer profile is awaiting Platform review',
      appointmentCancelled: 'A cancelled appointment needs follow-up',
      appointmentUpcoming: 'An appointment is coming up',
    },
    states: {
      loading: 'Loading data',
      error: 'This widget could not load its data.',
      empty: {
        trainers: 'No Trainer records are available.',
        assignments: 'No Trainer–Member assignments are available.',
        ptSales: 'No PT package purchases are available.',
        appointments: 'No appointments are available.',
        alerts: 'There are no operational alerts.',
      },
    },
    customization: {
      title: 'Customize dashboard',
      description: 'Choose which widgets are shown and arrange their order.',
      showWidget: 'Show',
      moveUp: 'Move up',
      moveDown: 'Move down',
      reset: 'Reset',
      cancel: 'Cancel',
      save: 'Save layout',
    },
    allHidden: 'Every dashboard widget is currently hidden.',
    showWidgets: 'Choose visible widgets',
  },
} as const;

export type GymOwnerDashboardCopy =
  (typeof gymOwnerDashboardCopy)[keyof typeof gymOwnerDashboardCopy];
