export const gymOwnerCustomersCopy = {
  vi: {
    pageLabel: 'Khách hàng / Người mua',
    readOnly: 'Chỉ xem dữ liệu vận hành',
    purchaser: 'Khách hàng / Người mua',
    purchase: 'Gói / Dịch vụ đã mua',
    order: 'Đơn hàng',
    processingStatus: 'Trạng thái xử lý nội bộ',
    gymOffer: 'Gym Offer',
    ptPackage: 'Gói PT',
    paymentSucceeded: 'Đã thanh toán',
    card: 'Thẻ',
    bankTransfer: 'Chuyển khoản',
    purchasedAt: 'Thời điểm mua',
    payment: 'Thanh toán',
    pendingGymConfirmation: 'Chờ Gym xác nhận',
    trainerAssignmentActive: 'Đã kích hoạt phân công Trainer',
    loading: 'Đang tải danh sách khách hàng',
    empty: 'Hiện chưa có hồ sơ khách hàng/người mua phục vụ vận hành.',
    error: 'Không thể tải danh sách khách hàng/người mua.',
  },
  en: {
    pageLabel: 'Customers / Purchasers',
    readOnly: 'Read-only operational data',
    purchaser: 'Customer / Purchaser',
    purchase: 'Purchased package / service',
    order: 'Order',
    processingStatus: 'Internal processing status',
    gymOffer: 'Gym Offer',
    ptPackage: 'PT Package',
    paymentSucceeded: 'Paid',
    card: 'Card',
    bankTransfer: 'Bank transfer',
    purchasedAt: 'Purchased',
    payment: 'Payment',
    pendingGymConfirmation: 'Pending Gym confirmation',
    trainerAssignmentActive: 'Trainer assignment active',
    loading: 'Loading customer records',
    empty: 'There are currently no operational customer/purchaser records.',
    error: 'The customer/purchaser list could not be loaded.',
  },
} as const;

export type GymOwnerCustomersCopy =
  (typeof gymOwnerCustomersCopy)[keyof typeof gymOwnerCustomersCopy];
