export const gymProfileCopy = {
  vi: {
    overview: 'Tổng quan hồ sơ',
    brand: 'Thông tin thương hiệu',
    branches: 'Chi nhánh',
    media: 'Ảnh bìa & thư viện',
    legal: 'Thông tin pháp lý',
    edit: 'Chỉnh sửa',
    manage: 'Quản lý',
    saved: 'Đã lưu thay đổi hồ sơ.',
    updatedAt: 'Cập nhật gần nhất',
    brandName: 'Tên thương hiệu',
    description: 'Mô tả trên Marketplace',
    contactPhone: 'Số điện thoại liên hệ',
    branchCount: 'Số chi nhánh',
    operatingHours: 'Giờ hoạt động',
    amenities: 'Tiện ích',
    address: 'Địa chỉ',
    city: 'Tỉnh / Thành phố',
    area: 'Khu vực',
    branchName: 'Tên chi nhánh',
    addBranch: 'Thêm chi nhánh',
    editBranch: 'Chỉnh sửa chi nhánh',
    viewBranch: 'Xem chi tiết',
    removeBranch: 'Xóa chi nhánh',
    removeTitle: 'Xóa chi nhánh này?',
    removeBody: 'Chi nhánh sẽ bị xóa khỏi hồ sơ Gym hiện tại.',
    keepBranch: 'Giữ chi nhánh',
    confirmRemove: 'Xác nhận xóa',
    primaryBranch: 'Chi nhánh chính',
    save: 'Lưu thay đổi',
    cancel: 'Hủy',
    required: 'Vui lòng điền đầy đủ các trường bắt buộc.',
    atLeastOne: 'Hồ sơ phải giữ ít nhất một chi nhánh.',
    noMedia: 'Chưa có ảnh bìa hoặc ảnh thư viện.',
    license: 'Giấy phép kinh doanh',
    approvedRecord: 'Thông tin đã được phê duyệt',
    legalNotice: 'Thay đổi thông tin pháp lý cần được gửi lại để xét duyệt.',
    facilities: [
      'Khu tạ tự do',
      'Khu cardio',
      'Khu functional',
      'Tủ đồ và phòng tắm',
      'Bãi đỗ xe',
      'Phòng xông hơi',
      'Khu phục hồi',
      'Đánh giá thể trạng',
    ],
  },
  en: {
    overview: 'Profile overview',
    brand: 'Brand information',
    branches: 'Branches',
    media: 'Cover & gallery',
    legal: 'Legal information',
    edit: 'Edit',
    manage: 'Manage',
    saved: 'Profile changes saved.',
    updatedAt: 'Last updated',
    brandName: 'Brand name',
    description: 'Marketplace description',
    contactPhone: 'Contact phone',
    branchCount: 'Branch count',
    operatingHours: 'Operating hours',
    amenities: 'Amenities',
    address: 'Address',
    city: 'Province / City',
    area: 'Area',
    branchName: 'Branch name',
    addBranch: 'Add branch',
    editBranch: 'Edit branch',
    viewBranch: 'View details',
    removeBranch: 'Remove branch',
    removeTitle: 'Remove this branch?',
    removeBody: 'The branch will be removed from the current Gym profile.',
    keepBranch: 'Keep branch',
    confirmRemove: 'Confirm removal',
    primaryBranch: 'Primary branch',
    save: 'Save changes',
    cancel: 'Cancel',
    required: 'Complete every required field.',
    atLeastOne: 'The profile must keep at least one branch.',
    noMedia: 'No cover or gallery images have been added.',
    license: 'Business license',
    approvedRecord: 'Approved information',
    legalNotice: 'Changes to legal information must be submitted for another review.',
    facilities: [
      'Free weights',
      'Cardio floor',
      'Functional zone',
      'Locker & shower',
      'Parking',
      'Sauna',
      'Recovery zone',
      'Body assessment',
    ],
  },
} as const;

export type GymProfileCopy = (typeof gymProfileCopy)[keyof typeof gymProfileCopy];
