export const platformCopy = {
  en: {
    role: 'Platform Admin',
    workspace: 'Platform workspace',
    dashboard: 'Dashboard',
    approvals: 'Approvals',
    marketplace: 'Marketplace',
    commercial: 'Commercial',
    campaigns: 'Campaigns',
    transactions: 'Transactions',
    analytics: 'Analytics',
    security: 'Security',
    movement: 'Assessment standards',
    overview: 'Operational overview',
    tenants: 'Tenants',
    movementAssessment: 'Exercise references',
    analyticsOverview: 'Legacy analytics',
    gymApplications: 'Gym applications',
    activeGyms: 'Active gyms',
    legalChanges: 'Legal changes',
    trainerApplications: 'Trainer applications',
    accountActions: 'Account actions',
    listings: 'Listing moderation',
    campaignsList: 'Campaign management',
    pricing: 'Commission & Plus',
    orders: 'Orders & settlement',
    settlementsList: 'Settlements',
    disputesList: 'Refunds & disputes',
    platformAnalytics: 'Platform analytics',
    activity: 'Audit & activity',
    notifications: 'Notifications',
    upcoming: 'Soon',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    sample: 'Sample data',
    customize: 'Customize dashboard',
    customizeTitle: 'Dashboard widgets',
    customizeDescription: 'Choose and order the operational sections shown on this device.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    showWidget: 'Show widget',
    reset: 'Reset',
    cancel: 'Cancel',
    save: 'Save',
    retry: 'Retry',
    loading: 'Loading dashboard',
    loadError: 'The dashboard could not be loaded.',
    noData: 'No operational items are available.',
    noWidgets: 'All widgets are hidden.',
    items: 'items',
    widgetTitles: {
      approvals: 'Pending approvals',
      moderation: 'Moderation queue',
      disputes: 'Open disputes',
      alerts: 'Operational alerts',
    },
    itemKinds: {
      gymApplication: 'Gym application',
      legalChange: 'Legal information change',
      trainerApplication: 'Trainer application',
      offerListing: 'Offer listing',
      trainerListing: 'Trainer listing',
      refundRequest: 'Refund request',
      orderDispute: 'Order dispute',
      settlementException: 'Settlement exception',
    },
    priority: {
      standard: 'Standard',
      attention: 'Needs attention',
      critical: 'Critical',
    },
  },
  vi: {
    role: 'Platform Admin',
    workspace: 'Không gian quản trị nền tảng',
    dashboard: 'Tổng quan',
    approvals: 'Phê duyệt',
    marketplace: 'Sàn dịch vụ',
    commercial: 'Thương mại',
    campaigns: 'Chiến dịch',
    transactions: 'Giao dịch',
    analytics: 'Phân tích',
    security: 'Bảo mật',
    movement: 'Tiêu chuẩn đánh giá',
    overview: 'Tình hình vận hành',
    tenants: 'Đơn vị vận hành',
    movementAssessment: 'Tham chiếu bài tập',
    analyticsOverview: 'Phân tích hiện có',
    gymApplications: 'Hồ sơ Gym',
    activeGyms: 'Gym đang hoạt động',
    legalChanges: 'Thay đổi pháp lý',
    trainerApplications: 'Hồ sơ Trainer',
    accountActions: 'Tài khoản',
    listings: 'Kiểm duyệt listing',
    campaignsList: 'Quản lý chiến dịch',
    pricing: 'Hoa hồng & Plus',
    orders: 'Đơn hàng & đối soát',
    settlementsList: 'Đối soát',
    disputesList: 'Hoàn tiền & tranh chấp',
    platformAnalytics: 'Phân tích nền tảng',
    activity: 'Nhật ký hoạt động',
    notifications: 'Thông báo',
    upcoming: 'Sắp tới',
    openMenu: 'Mở điều hướng',
    closeMenu: 'Đóng điều hướng',
    sample: 'Dữ liệu minh họa',
    customize: 'Tùy chỉnh dashboard',
    customizeTitle: 'Các khối dashboard',
    customizeDescription: 'Chọn và sắp xếp các khối vận hành hiển thị trên thiết bị này.',
    moveUp: 'Chuyển lên',
    moveDown: 'Chuyển xuống',
    showWidget: 'Hiển thị khối',
    reset: 'Đặt lại',
    cancel: 'Hủy',
    save: 'Lưu',
    retry: 'Thử lại',
    loading: 'Đang tải dashboard',
    loadError: 'Không thể tải dashboard.',
    noData: 'Hiện không có việc vận hành cần hiển thị.',
    noWidgets: 'Tất cả các khối đang được ẩn.',
    items: 'mục',
    widgetTitles: {
      approvals: 'Chờ phê duyệt',
      moderation: 'Chờ kiểm duyệt',
      disputes: 'Tranh chấp đang mở',
      alerts: 'Cảnh báo vận hành',
    },
    itemKinds: {
      gymApplication: 'Hồ sơ Gym',
      legalChange: 'Thay đổi pháp lý',
      trainerApplication: 'Hồ sơ Trainer',
      offerListing: 'Ưu đãi đăng bán',
      trainerListing: 'Hồ sơ Trainer hiển thị',
      refundRequest: 'Yêu cầu hoàn tiền',
      orderDispute: 'Tranh chấp đơn hàng',
      settlementException: 'Ngoại lệ đối soát',
    },
    priority: {
      standard: 'Thông thường',
      attention: 'Cần chú ý',
      critical: 'Nghiêm trọng',
    },
  },
} as const;

export type PlatformCopy = (typeof platformCopy)['en'] | (typeof platformCopy)['vi'];
