export const gymOwnerAnalyticsCopy = {
  vi: {
    pageTitle: 'Phân tích hiệu quả vận hành',
    backendNotice:
      'Tất cả KPI và số liệu so sánh do backend cung cấp. Frontend không tự tính KPI tài chính.',
    range: 'Khoảng thời gian',
    last7Days: '7 ngày',
    last30Days: '30 ngày',
    last90Days: '90 ngày',
    custom: 'Tùy chọn',
    startDate: 'Từ ngày',
    endDate: 'Đến ngày',
    apply: 'Áp dụng',
    rangeRequired: 'Chọn đủ ngày bắt đầu và ngày kết thúc.',
    rangeOrder: 'Ngày bắt đầu không được sau ngày kết thúc.',
    currentPeriod: 'Kỳ hiện tại',
    previousPeriod: 'Kỳ trước',
    timezone: 'Múi giờ Asia/Bangkok · tính cả ngày bắt đầu và kết thúc',
    sales: 'Doanh số dịch vụ Gym',
    views: 'Lượt xem gói PT',
    purchases: 'Đơn mua thành công',
    assignments: 'Phân công mới',
    trainerActivity: 'Buổi PT hoàn thành',
    unavailable: 'Backend chưa trả dữ liệu',
    previous: 'Kỳ trước',
    absoluteChange: 'Thay đổi',
    percentageChange: 'Tỷ lệ',
    comparisonUnavailable: 'Không có tỷ lệ so sánh',
    commercialTrend: 'Xu hướng thương mại',
    assignmentTrend: 'Xu hướng phân công Trainer–Member',
    activityByTrainer: 'Hoạt động Trainer',
    completedAppointmentsOnly: 'Chỉ tính lịch hẹn PT đã hoàn thành',
    trainer: 'Trainer',
    completedAppointments: 'Đã hoàn thành',
    change: 'So với kỳ trước',
    currentSeries: 'Kỳ hiện tại',
    previousSeries: 'Kỳ trước',
    loading: 'Đang tải dữ liệu phân tích',
    empty: 'Không có dữ liệu phân tích cho khoảng thời gian này.',
    error: 'Không thể tải dữ liệu phân tích.',
    partial: 'Một phần dữ liệu chưa được backend cung cấp; các chỉ số còn lại vẫn được hiển thị.',
    sampleRange: 'Dữ liệu local hiện có cho 01/09/2026–15/09/2026.',
  },
  en: {
    pageTitle: 'Operational analytics',
    backendNotice:
      'All KPIs and comparison values are supplied by the backend. The frontend does not calculate financial KPIs.',
    range: 'Date range',
    last7Days: '7 days',
    last30Days: '30 days',
    last90Days: '90 days',
    custom: 'Custom',
    startDate: 'Start date',
    endDate: 'End date',
    apply: 'Apply',
    rangeRequired: 'Select both a start date and an end date.',
    rangeOrder: 'The start date cannot be after the end date.',
    currentPeriod: 'Current period',
    previousPeriod: 'Previous period',
    timezone: 'Asia/Bangkok timezone · start and end dates are inclusive',
    sales: 'Gym service sales',
    views: 'PT Package views',
    purchases: 'Successful purchases',
    assignments: 'New assignments',
    trainerActivity: 'Completed PT appointments',
    unavailable: 'Not supplied by backend',
    previous: 'Previous period',
    absoluteChange: 'Change',
    percentageChange: 'Rate',
    comparisonUnavailable: 'Comparison rate unavailable',
    commercialTrend: 'Commercial trend',
    assignmentTrend: 'Trainer–Member assignment trend',
    activityByTrainer: 'Trainer activity',
    completedAppointmentsOnly: 'Completed PT appointments only',
    trainer: 'Trainer',
    completedAppointments: 'Completed',
    change: 'Versus previous period',
    currentSeries: 'Current period',
    previousSeries: 'Previous period',
    loading: 'Loading analytics',
    empty: 'No analytics data is available for this date range.',
    error: 'Analytics data could not be loaded.',
    partial: 'Some data was not supplied by the backend; available metrics remain visible.',
    sampleRange: 'Local data is available for 01/09/2026–15/09/2026.',
  },
} as const;

export type GymOwnerAnalyticsCopy =
  (typeof gymOwnerAnalyticsCopy)[keyof typeof gymOwnerAnalyticsCopy];
