export const gymOwnerOrdersCopy = {
  vi: {
    ordersLabel: 'Đơn hàng',
    settlementsLabel: 'Kỳ đối soát',
    platformValues: 'Giá trị do Platform cung cấp',
    readOnlySettlement: 'Đối soát chỉ xem',
    exportOrders: 'Xuất CSV đơn hàng',
    exportSettlements: 'Xuất CSV đối soát',
    order: 'Đơn hàng',
    item: 'Dịch vụ / Gói',
    purchasedAt: 'Ngày mua',
    gymServicePrice: 'Giá dịch vụ Gym',
    discount: 'Giảm giá',
    aiPlus: 'AI Plus',
    commission: 'Hoa hồng Platform',
    netReceived: 'Gym thực nhận',
    status: 'Trạng thái',
    actions: 'Thao tác',
    viewDetail: 'Xem chi tiết',
    gymOffer: 'Gym Offer',
    ptPackage: 'Gói PT',
    paid: 'Đã thanh toán',
    paymentFailed: 'Thanh toán thất bại',
    pendingGymConfirmation: 'Chờ Gym xác nhận',
    trainerAssignmentActive: 'Đã kích hoạt phân công Trainer',
    financialBreakdown: 'Phân tách tài chính',
    orderInformation: 'Thông tin đơn hàng',
    purchaser: 'Người mua',
    paymentMethod: 'Phương thức thanh toán',
    card: 'Thẻ',
    bankTransfer: 'Chuyển khoản',
    settlementPeriod: 'Kỳ đối soát',
    backToOrders: 'Quay lại đơn hàng',
    requestRefundDispute: 'Gửi yêu cầu refund / dispute',
    requestTitle: 'Yêu cầu Platform xem xét',
    requestDescription: 'Gym Owner chỉ gửi yêu cầu. Platform là bên xem xét và xử lý.',
    requestType: 'Loại yêu cầu',
    refund: 'Refund',
    dispute: 'Dispute',
    requestDetails: 'Lý do / thông tin hỗ trợ',
    requestPlaceholder: 'Mô tả vấn đề cần Platform xem xét',
    requestRequired: 'Vui lòng nhập lý do hoặc thông tin hỗ trợ.',
    cancel: 'Hủy',
    submitRequest: 'Gửi cho Platform',
    requestSubmitted: 'Yêu cầu đã được gửi đến Platform.',
    submittedRequest: 'Yêu cầu đã gửi',
    platformReview: 'Chờ Platform xem xét',
    period: 'Kỳ',
    orders: 'Số đơn hàng',
    reconciliation: 'Đối soát',
    backendNotice:
      'Frontend chỉ hiển thị dữ liệu tài chính và trạng thái do backend cung cấp, không tự tính toán.',
    loadingOrders: 'Đang tải đơn hàng',
    emptyOrders: 'Hiện chưa có đơn hàng thương mại.',
    errorOrders: 'Không thể tải danh sách đơn hàng.',
    loadingSettlements: 'Đang tải các kỳ đối soát',
    emptySettlements: 'Hiện chưa có dữ liệu đối soát.',
    errorSettlements: 'Không thể tải dữ liệu đối soát.',
    orderNotFound: 'Không tìm thấy đơn hàng.',
  },
  en: {
    ordersLabel: 'Orders',
    settlementsLabel: 'Settlement periods',
    platformValues: 'Platform-provided values',
    readOnlySettlement: 'Read-only settlement',
    exportOrders: 'Export orders CSV',
    exportSettlements: 'Export settlements CSV',
    order: 'Order',
    item: 'Service / Package',
    purchasedAt: 'Purchased',
    gymServicePrice: 'Gym service price',
    discount: 'Discount',
    aiPlus: 'AI Plus',
    commission: 'Platform commission',
    netReceived: 'Net received by Gym',
    status: 'Status',
    actions: 'Actions',
    viewDetail: 'View detail',
    gymOffer: 'Gym Offer',
    ptPackage: 'PT Package',
    paid: 'Paid',
    paymentFailed: 'Payment failed',
    pendingGymConfirmation: 'Pending Gym confirmation',
    trainerAssignmentActive: 'Trainer assignment active',
    financialBreakdown: 'Financial breakdown',
    orderInformation: 'Order information',
    purchaser: 'Purchaser',
    paymentMethod: 'Payment method',
    card: 'Card',
    bankTransfer: 'Bank transfer',
    settlementPeriod: 'Settlement period',
    backToOrders: 'Back to orders',
    requestRefundDispute: 'Submit refund / dispute request',
    requestTitle: 'Request Platform review',
    requestDescription: 'The Gym Owner submits a request. Platform reviews and processes it.',
    requestType: 'Request type',
    refund: 'Refund',
    dispute: 'Dispute',
    requestDetails: 'Reason / supporting information',
    requestPlaceholder: 'Describe the issue that Platform should review',
    requestRequired: 'Provide a reason or supporting information.',
    cancel: 'Cancel',
    submitRequest: 'Send to Platform',
    requestSubmitted: 'The request was sent to Platform.',
    submittedRequest: 'Submitted request',
    platformReview: 'Awaiting Platform review',
    period: 'Period',
    orders: 'Orders',
    reconciliation: 'Reconciliation',
    backendNotice:
      'The frontend displays financial values and statuses supplied by the backend without calculating them.',
    loadingOrders: 'Loading orders',
    emptyOrders: 'There are currently no commercial orders.',
    errorOrders: 'The order list could not be loaded.',
    loadingSettlements: 'Loading settlement periods',
    emptySettlements: 'There are currently no settlement records.',
    errorSettlements: 'The settlement records could not be loaded.',
    orderNotFound: 'The order could not be found.',
  },
} as const;

export type GymOwnerOrdersCopy = (typeof gymOwnerOrdersCopy)[keyof typeof gymOwnerOrdersCopy];
