export const commercialCopy = {
  en: {
    sample: 'Sample data',
    configuration: 'Commercial configuration',
    commission: 'Platform commission',
    effectiveAt: 'Effective from',
    rate: 'Commission rate',
    save: 'Save configuration',
    history: 'Version history',
    plus: 'AI Plus pricing',
    standalone: 'Standalone price',
    bundled: 'Bundled price',
    partner: 'Partner price',
    priceRule: 'Bundled and partner prices cannot exceed the standalone price.',
    invalidCommission: 'Enter a non-negative rate and a future effective date.',
    invalidPlus: 'Enter valid non-negative prices; bundled and partner cannot exceed standalone.',
    confirmation: 'Confirm configuration change?',
    confirmationDescription:
      'This records a new Platform configuration. It applies only to new transactions from its effective date.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    orders: 'Orders',
    settlements: 'Settlements',
    detail: 'Detail',
    back: 'Back to list',
    export: 'Export CSV',
    gymService: 'Gym service price',
    discount: 'Discount',
    aiPlus: 'AI Plus',
    commissionValue: 'Commission',
    netReceived: 'Net received',
    backend:
      'Backend-provided financial values. No calculation or transaction editing occurs in this screen.',
    item: 'Item',
    purchaser: 'Purchaser',
    status: 'Status',
    period: 'Period',
    orderCount: 'Orders',
    reconciled: 'Reconciled',
    inReview: 'In review',
    paid: 'Paid',
    refunded: 'Refunded',
    noOrders: 'There are no orders to show.',
    noSettlements: 'There are no settlements to show.',
  },
  vi: {
    sample: 'Dữ liệu minh họa',
    configuration: 'Cấu hình thương mại',
    commission: 'Hoa hồng nền tảng',
    effectiveAt: 'Có hiệu lực từ',
    rate: 'Tỷ lệ hoa hồng',
    save: 'Lưu cấu hình',
    history: 'Lịch sử phiên bản',
    plus: 'Giá AI Plus',
    standalone: 'Giá standalone',
    bundled: 'Giá bundled',
    partner: 'Giá partner',
    priceRule: 'Giá bundled và partner không được vượt giá standalone.',
    invalidCommission: 'Nhập tỷ lệ không âm và ngày hiệu lực trong tương lai.',
    invalidPlus: 'Nhập giá không âm; bundled và partner không được vượt standalone.',
    confirmation: 'Xác nhận thay đổi cấu hình?',
    confirmationDescription:
      'Thao tác ghi nhận cấu hình Platform mới. Nó chỉ áp dụng cho giao dịch mới từ ngày hiệu lực.',
    cancel: 'Hủy',
    confirm: 'Xác nhận',
    orders: 'Đơn hàng',
    settlements: 'Đối soát',
    detail: 'Chi tiết',
    back: 'Quay lại danh sách',
    export: 'Xuất CSV',
    gymService: 'Giá dịch vụ Gym',
    discount: 'Giảm giá',
    aiPlus: 'AI Plus',
    commissionValue: 'Hoa hồng',
    netReceived: 'Thực nhận',
    backend:
      'Các giá trị tài chính do backend cung cấp. Trang này không tính lại hoặc sửa giao dịch.',
    item: 'Sản phẩm',
    purchaser: 'Người mua',
    status: 'Trạng thái',
    period: 'Kỳ',
    orderCount: 'Đơn hàng',
    reconciled: 'Đã đối soát',
    inReview: 'Đang rà soát',
    paid: 'Đã thanh toán',
    refunded: 'Đã hoàn tiền',
    noOrders: 'Không có đơn hàng để hiển thị.',
    noSettlements: 'Không có dữ liệu đối soát.',
  },
} as const;
export type CommercialCopy = (typeof commercialCopy)['en'] | (typeof commercialCopy)['vi'];
