import type { WorkoutPlanPreview } from './types';

export const featuredWorkout = Object.freeze({
  id: 'upper-body-matrix',
  code: 'PRT-2025-UPP-04',
  category: 'hypertrophy' as const,
  stations: 8,
  durationMinutes: 48,
  calories: 420,
  tier: 'ADV',
  completedSets: 16,
  totalSets: 25,
  progress: 64,
});

export const demoWorkoutPlans: ReadonlyArray<WorkoutPlanPreview> = Object.freeze([
  {
    id: 'foundation',
    code: 'PRT-01',
    category: 'strength',
    level: 'beginner',
    stations: 6,
    durationMinutes: 35,
    apparatus: 'DB & Bench',
    progress: 100,
    status: 'completed',
  },
  {
    id: 'posterior',
    code: 'PRT-02',
    category: 'strength',
    level: 'advanced',
    stations: 7,
    durationMinutes: 50,
    apparatus: 'BB & Rack',
    progress: 40,
    completedSets: 8,
    totalSets: 20,
    status: 'active',
  },
  {
    id: 'chest',
    code: 'PRT-03',
    category: 'hypertrophy',
    level: 'intermediate',
    stations: 6,
    durationMinutes: 42,
    apparatus: 'Incline & Cable',
    progress: 0,
    status: 'ready',
  },
  {
    id: 'core',
    code: 'PRT-04',
    category: 'metabolic',
    level: 'allLevels',
    stations: 5,
    durationMinutes: 28,
    apparatus: 'Body & Mats',
    progress: 15,
    completedSets: 3,
    totalSets: 18,
    status: 'active',
  },
  {
    id: 'olympic',
    code: 'PRT-05',
    category: 'strength',
    level: 'elite',
    stations: 6,
    durationMinutes: 55,
    apparatus: 'Barbell & Plates',
    progress: 0,
    status: 'ready',
  },
  {
    id: 'deltoid',
    code: 'PRT-06',
    category: 'hypertrophy',
    level: 'intermediate',
    stations: 7,
    durationMinutes: 45,
    apparatus: 'DB & Cables',
    progress: 80,
    completedSets: 20,
    totalSets: 25,
    status: 'active',
  },
]);
