import type {
  GymAssignmentException,
  GymPTPackage,
  GymTrainerAssignment,
  GymTrainerProfile,
} from './types';

export const seedGymTrainers: GymTrainerProfile[] = [
  {
    id: 'trainer-minh',
    fullName: 'Minh Tran',
    email: 'minh.tran@fit.local',
    phone: '+84 912 767 338',
    bio: 'Strength coach focused on safe technique and sustainable progression.',
    specializations: ['strength', 'hypertrophy'],
    experienceYears: 7,
    selfIntroduction:
      'I help members build repeatable strength habits and understand every progression.',
    avatarDataUrl: null,
    approvalStatus: 'approved',
    operationalStatus: 'active',
    rejectionReason: null,
    submittedAt: '2026-09-05T08:30:00.000Z',
    createdAt: '2026-09-03T08:30:00.000Z',
  },
  {
    id: 'trainer-hana',
    fullName: 'Hana Kim',
    email: 'hana.kim@fit.local',
    phone: '+84 904 318 670',
    bio: 'Coach for progressive fat-loss and conditioning programs.',
    specializations: ['fat_loss', 'endurance'],
    experienceYears: 6,
    selfIntroduction: 'My coaching combines practical conditioning with clear weekly decisions.',
    avatarDataUrl: null,
    approvalStatus: 'approved',
    operationalStatus: 'hidden',
    rejectionReason: null,
    submittedAt: '2026-08-20T10:00:00.000Z',
    createdAt: '2026-08-19T09:00:00.000Z',
  },
  {
    id: 'trainer-linh',
    fullName: 'Linh Pham',
    email: 'linh.pham@fit.local',
    phone: '+84 906 420 175',
    bio: 'Movement and mobility coach for beginner-friendly training.',
    specializations: ['movement', 'mobility'],
    experienceYears: 5,
    selfIntroduction: 'I make movement practice approachable and measurable.',
    avatarDataUrl: null,
    approvalStatus: 'approved',
    operationalStatus: 'suspended',
    rejectionReason: null,
    submittedAt: '2026-08-16T08:00:00.000Z',
    createdAt: '2026-08-14T08:00:00.000Z',
  },
  {
    id: 'trainer-quang',
    fullName: 'Quang Pham',
    email: 'quang.pham@fit.local',
    phone: '+84 909 115 804',
    bio: 'Hypertrophy coach with a structured progression approach.',
    specializations: ['hypertrophy'],
    experienceYears: 4,
    selfIntroduction: 'I focus on clear execution and progressive volume.',
    avatarDataUrl: null,
    approvalStatus: 'pending',
    operationalStatus: null,
    rejectionReason: null,
    submittedAt: '2026-09-29T10:30:00.000Z',
    createdAt: '2026-09-28T08:30:00.000Z',
  },
  {
    id: 'trainer-nam',
    fullName: 'Nam Le',
    email: 'nam.le@fit.local',
    phone: '+84 902 774 221',
    bio: 'Strength and exercise rehabilitation coach.',
    specializations: ['strength', 'rehabilitation'],
    experienceYears: 5,
    selfIntroduction: 'I coach careful return-to-training progressions.',
    avatarDataUrl: null,
    approvalStatus: 'rejected',
    operationalStatus: null,
    rejectionReason: 'Professional experience information could not be verified.',
    submittedAt: '2026-09-23T09:10:00.000Z',
    createdAt: '2026-09-21T09:10:00.000Z',
  },
  {
    id: 'trainer-jordan',
    fullName: 'Jordan Lee',
    email: 'jordan.lee@fit.local',
    phone: '+84 901 772 641',
    bio: 'Former endurance coach.',
    specializations: ['endurance'],
    experienceYears: 8,
    selfIntroduction: 'Historical Trainer record retained for operational history.',
    avatarDataUrl: null,
    approvalStatus: 'approved',
    operationalStatus: 'unlinked',
    rejectionReason: null,
    submittedAt: '2025-06-20T09:00:00.000Z',
    createdAt: '2025-06-18T09:00:00.000Z',
  },
];

export const seedTrainerAssignments: GymTrainerAssignment[] = [
  {
    id: 'assignment-alex',
    memberName: 'Alex Volkov',
    memberEmail: 'alex@fit.local',
    packageName: 'Strength Foundation · 8 sessions',
    trainerId: 'trainer-minh',
    startsOn: '2026-09-13',
    endsOn: '2026-10-27',
    status: 'active',
  },
  {
    id: 'assignment-mai',
    memberName: 'Mai Nguyen',
    memberEmail: 'mai@fit.local',
    packageName: 'Conditioning Reset · 10 sessions',
    trainerId: 'trainer-linh',
    startsOn: '2026-09-20',
    endsOn: '2026-11-04',
    status: 'active',
  },
  {
    id: 'assignment-jordan',
    memberName: 'Jordan Lee',
    memberEmail: 'jordan@fit.local',
    packageName: 'Endurance Reset · 10 sessions',
    trainerId: 'trainer-jordan',
    startsOn: '2026-07-23',
    endsOn: '2026-09-23',
    status: 'historical',
  },
];

export const seedAssignmentExceptions: GymAssignmentException[] = [
  {
    id: 'exception-mai',
    memberName: 'Mai Nguyen',
    memberEmail: 'mai@fit.local',
    packageName: 'Conditioning Reset · 10 sessions',
    originalTrainerId: 'trainer-linh',
    reason: 'trainerUnavailable',
    status: 'open',
    replacementTrainerId: null,
    createdAt: '2026-10-01T07:30:00.000Z',
    resolvedAt: null,
  },
  {
    id: 'exception-history',
    memberName: 'Hana Kim',
    memberEmail: 'hana.member@fit.local',
    packageName: 'Strength Foundation · 8 sessions',
    originalTrainerId: 'trainer-jordan',
    reason: 'activationFailed',
    status: 'resolved',
    replacementTrainerId: 'trainer-minh',
    createdAt: '2026-09-18T08:00:00.000Z',
    resolvedAt: '2026-09-18T10:15:00.000Z',
  },
];

export const seedGymPTPackages: GymPTPackage[] = [
  {
    id: 'package-strength-8',
    trainerId: 'trainer-minh',
    name: {
      en: 'Strength Foundation · 8 sessions',
      vi: 'Nền tảng sức mạnh · 8 buổi',
    },
    sessionsIncluded: 8,
    durationDays: 45,
    servicePriceVnd: 3_600_000,
    features: [
      { en: 'Initial assessment', vi: 'Đánh giá đầu kỳ' },
      { en: 'Personal workout plan', vi: 'Kế hoạch tập cá nhân' },
    ],
    publicationStatus: 'published',
    createdAt: '2026-09-06T08:00:00.000Z',
    updatedAt: '2026-09-06T08:00:00.000Z',
  },
  {
    id: 'package-progress-16',
    trainerId: 'trainer-minh',
    name: {
      en: 'Progress Coaching · 16 sessions',
      vi: 'Huấn luyện tiến bộ · 16 buổi',
    },
    sessionsIncluded: 16,
    durationDays: 90,
    servicePriceVnd: 6_600_000,
    features: [
      { en: 'Progress reviews', vi: 'Đánh giá tiến độ' },
      { en: 'Plan adjustments', vi: 'Điều chỉnh kế hoạch' },
    ],
    publicationStatus: 'draft',
    createdAt: '2026-09-25T08:00:00.000Z',
    updatedAt: '2026-09-25T08:00:00.000Z',
  },
];
